name: Python Flask CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest -v

      - name: Build Docker Image
        run: |
          docker build -t flask-app .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd aws-devops-cicd-project
            git pull origin main

            docker stop flask-container || true
            docker rm flask-container || true

            docker build -t flask-app .

            docker run -d \
              --restart unless-stopped \
              -p 5000:5000 \
              --name flask-container \
              flask-app